# Generated by Django 4.2.23 on 2025-08-18 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('item_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WorldItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.item')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.actor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.item')),
            ],
            options={
                'unique_together': {('actor', 'item')},
            },
        ),
    ]
